version: '3'

services:
  ric-dev:
    container_name: ric_dev
    build: .
    ports:
      - "8005:8005"
      - "40000:40000"
    volumes:
      - ./:/ric
      - ./docker/go:/root/go
      - ./docker/go/src/github.com/phzfi/RIC/server:/root/go/src/github.com/phzfi/RIC/server
      - ./config/host_whitelist.ini:/var/lib/ric/config/host_whitelist.ini
      - ./config/ric_config.ini:/etc/ric/ric_config.ini

    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    command: tail -f /dev/null # Keeps docker-compose from terminating process
